import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:project_color_palette/generator/palette_exception.dart';
import 'package:project_color_palette/generator/palette_options.dart';
import 'package:project_color_palette/generator/palette_source_builder.dart';

String generate(
  String csv, {
  String fileName = 'color_test.csv',
  PaletteOptions options = const PaletteOptions(),
  List<String>? warnings,
}) {
  return PaletteSourceBuilder(options: options).build(
    csvFileName: fileName,
    csvContent: csv,
    onWarning: warnings?.add,
  );
}

void main() {
  group('golden output', () {
    test('a multi-color palette closes its class exactly once', () {
      // Regression: `buffer.writeln('}')` used to sit inside the row loop, so
      // any CSV with more than one color produced uncompilable Dart. Every
      // committed example happened to have exactly one row.
      final source = generate(
        'alias,value,description\n'
        'text/primary,#212529,Default body text\n'
        'gray-100,#F1F3F5,\n'
        'overlay/scrim,#00000080,50% black\n',
        fileName: 'semantic_light.csv',
      );

      expect(source, '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by project_color_palette from 'semantic_light.csv'.
//
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:flutter/material.dart';

/// Color palette generated from `semantic_light.csv`.
///
/// Contains 3 colors.
class SemanticLight {
  const SemanticLight._();

  /// `text/primary` - Default body text
  static const Color textPrimary = Color(0xFF212529);

  /// `gray-100`
  static const Color gray100 = Color(0xFFF1F3F5);

  /// `overlay/scrim` - 50% black
  static const Color overlayScrim = Color(0x80000000);

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{
    'text/primary': textPrimary,
    'gray-100': gray100,
    'overlay/scrim': overlayScrim,
  };
}
''');
    });

    test('a palette with no data rows is still valid Dart', () {
      // Regression: zero rows used to emit `class X {` with no closing brace.
      final warnings = <String>[];
      final source = generate(
        'name,value,comment\n',
        fileName: 'color_empty.csv',
        warnings: warnings,
      );

      expect(source, '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by project_color_palette from 'color_empty.csv'.
//
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:flutter/material.dart';

/// Color palette generated from `color_empty.csv`.
///
/// Contains 0 colors.
class ColorEmpty {
  const ColorEmpty._();

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{};
}
''');
      expect(warnings, isEmpty);
    });

    test('an entirely empty file generates an empty palette and warns', () {
      final warnings = <String>[];
      final source = generate('', warnings: warnings);
      expect(source, contains('class ColorTest {'));
      expect(source.split('\n').where((line) => line == '}').length, 1);
      expect(warnings.single, contains('empty'));
    });
  });

  group('theme modes', () {
    test('light and dark columns generate two classes and an extension', () {
      final source = generate(
        'alias,light,dark\n'
        'text/primary,#212529,#F1F3F5\n'
        'action/primary,#2C6BED,#4C8DFF\n',
        fileName: 'semantic.csv',
      );

      expect(source, '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by project_color_palette from 'semantic.csv'.
//
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:flutter/material.dart';

/// Color palette generated from `semantic.csv` (light mode).
///
/// Contains 2 colors.
class SemanticLight {
  const SemanticLight._();

  /// `text/primary`
  static const Color textPrimary = Color(0xFF212529);

  /// `action/primary`
  static const Color actionPrimary = Color(0xFF2C6BED);

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{
    'text/primary': textPrimary,
    'action/primary': actionPrimary,
  };
}

/// Color palette generated from `semantic.csv` (dark mode).
///
/// Contains 2 colors.
class SemanticDark {
  const SemanticDark._();

  /// `text/primary`
  static const Color textPrimary = Color(0xFFF1F3F5);

  /// `action/primary`
  static const Color actionPrimary = Color(0xFF4C8DFF);

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{
    'text/primary': textPrimary,
    'action/primary': actionPrimary,
  };
}

/// The palette above, resolved through the active theme.
///
/// Register it once:
///
/// ```dart
/// ThemeData(extensions: const [Semantic.light])
/// ```
///
/// then read it with `Semantic.of(context).textPrimary`.
class Semantic extends ThemeExtension<Semantic> {
  const Semantic({required this.textPrimary, required this.actionPrimary});

  /// The light mode palette.
  static const Semantic light = Semantic(
    textPrimary: SemanticLight.textPrimary,
    actionPrimary: SemanticLight.actionPrimary,
  );

  /// The dark mode palette.
  static const Semantic dark = Semantic(
    textPrimary: SemanticDark.textPrimary,
    actionPrimary: SemanticDark.actionPrimary,
  );

  /// `text/primary`
  final Color textPrimary;

  /// `action/primary`
  final Color actionPrimary;

  /// The palette registered on the closest [Theme].
  static Semantic of(BuildContext context) =>
      Theme.of(context).extension<Semantic>()!;

  @override
  Semantic copyWith({Color? textPrimary, Color? actionPrimary}) {
    return Semantic(
      textPrimary: textPrimary ?? this.textPrimary,
      actionPrimary: actionPrimary ?? this.actionPrimary,
    );
  }

  @override
  Semantic lerp(covariant ThemeExtension<Semantic>? other, double t) {
    if (other is! Semantic) return this;
    return Semantic(
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      actionPrimary: Color.lerp(actionPrimary, other.actionPrimary, t)!,
    );
  }
}
''');
    });

    test('a single value column is unaffected by mode support', () {
      final source = generate('name,value\nWhite,#FFFFFF\n');
      expect(source, contains('class ColorTest {'));
      expect(source, isNot(contains('ThemeExtension')));
      expect(source, isNot(contains('ColorTestLight')));
    });

    test('day and night are accepted as mode labels', () {
      final source = generate(
        'alias,day,night\ntext/primary,#212529,#F1F3F5\n',
        fileName: 'semantic.csv',
      );
      expect(source, contains('class SemanticLight {'));
      expect(source, contains('class SemanticDark {'));
    });

    test('mode columns win over a leftover value column', () {
      final source = generate(
        'alias,value,light,dark\n'
        'text/primary,#000000,#212529,#F1F3F5\n',
        fileName: 'semantic.csv',
      );
      expect(
          source,
          contains('static const Color textPrimary = '
              'Color(0xFF212529);'));
      expect(source, isNot(contains('0xFF000000')));
    });

    test('one named mode generates one class and no extension', () {
      final source = generate(
        'alias,light\ntext/primary,#212529\n',
        fileName: 'semantic.csv',
      );
      expect(source, contains('class SemanticLight {'));
      expect(source, isNot(contains('ThemeExtension')));
    });

    test('a missing value in one mode is an error naming that mode', () {
      expect(
        () => generate(
          'alias,light,dark\ntext/primary,#212529,\n',
          fileName: 'semantic.csv',
        ),
        throwsA(isA<PaletteFormatException>().having(
          (e) => e.message,
          'message',
          allOf(contains('row 2'), contains('dark')),
        )),
      );
    });

    test('an unparseable value names the row and the mode', () {
      expect(
        () => generate(
          'alias,light,dark\ntext/primary,#212529,not-a-color\n',
          fileName: 'semantic.csv',
        ),
        throwsA(isA<PaletteFormatException>().having(
          (e) => e.message,
          'message',
          allOf(contains('row 2'), contains('(dark)')),
        )),
      );
    });

    test('two columns for the same mode is an error', () {
      expect(
        () => generate(
          'alias,light,light mode\ntext/primary,#212529,#000000\n',
          fileName: 'semantic.csv',
        ),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('more than one'))),
      );
    });

    test('aliases colliding with the extension API are pushed aside', () {
      final source = generate(
        'alias,light,dark\n'
        'light,#FFFFFF,#000000\n'
        'copyWith,#FFFFFE,#000001\n'
        'of,#FFFFFD,#000002\n',
        fileName: 'semantic.csv',
      );
      for (final name in ['colorLight', 'colorCopyWith', 'colorOf']) {
        expect(source, contains('static const Color $name = '));
      }
    });
  });

  group('alias references', () {
    /// The folder index the build step assembles from every sibling CSV.
    Map<String, List<AliasValueSource>> indexOf(Map<String, String> files) {
      final index = <String, List<AliasValueSource>>{};
      files.forEach((fileName, content) {
        scanAliases(fileName, content).forEach((alias, source) {
          index.putIfAbsent(alias, () => <AliasValueSource>[]).add(source);
        });
      });
      return index;
    }

    String generateWith(
      String csv, {
      required Map<String, String> siblings,
      String fileName = 'semantic.csv',
    }) {
      return PaletteSourceBuilder(
        aliasIndex: indexOf({fileName: csv, ...siblings}),
      ).build(csvFileName: fileName, csvContent: csv);
    }

    const primitives = 'name,value\n'
        'gray-900,#212529\n'
        'gray-100,#F1F3F5\n'
        'blue-500,#2C6BED\n';

    test('a reference resolves to the hex of the alias it names', () {
      final source = generateWith(
        'alias,value\ntext/primary,{gray-900}\n',
        siblings: const {'color_primitive.csv': primitives},
      );
      expect(
          source,
          contains('static const Color textPrimary = '
              'Color(0xFF212529);'));
    });

    test('references work per mode', () {
      final source = generateWith(
        'alias,light,dark\ntext/primary,{gray-900},{gray-100}\n',
        siblings: const {'color_primitive.csv': primitives},
      );
      expect(source, contains('class SemanticLight'));
      expect(source, contains('Color(0xFF212529)'));
      expect(source, contains('Color(0xFFF1F3F5)'));
    });

    test('a mode reference to a palette with no modes uses its one value', () {
      final source = generateWith(
        'alias,light,dark\naction/primary,{blue-500},{blue-500}\n',
        siblings: const {'color_primitive.csv': primitives},
      );
      expect(source.split('Color(0xFF2C6BED)').length - 1, greaterThan(1));
    });

    test('references and literals mix freely', () {
      final source = generateWith(
        'alias,value\ntext/primary,{gray-900}\nborder,#DEE2E6\n',
        siblings: const {'color_primitive.csv': primitives},
      );
      expect(source, contains('Color(0xFF212529)'));
      expect(source, contains('Color(0xFFDEE2E6)'));
    });

    test('a reference within the same file resolves', () {
      final source = generateWith(
        'alias,value\nblue-500,#2C6BED\naction/primary,{blue-500}\n',
        siblings: const {},
      );
      expect(
          source,
          contains('static const Color actionPrimary = '
              'Color(0xFF2C6BED);'));
    });

    test('a chain of references resolves', () {
      final source = generateWith(
        'alias,value\ntext/brand,{action/primary}\n',
        siblings: const {
          'color_primitive.csv': primitives,
          'semantic_base.csv': 'name,value\naction/primary,{blue-500}\n',
        },
      );
      expect(source, contains('Color(0xFF2C6BED)'));
    });

    test('an unknown reference is an error naming the row', () {
      expect(
        () => generateWith(
          'alias,value\ntext/primary,{nope}\n',
          siblings: const {'color_primitive.csv': primitives},
        ),
        throwsA(isA<PaletteFormatException>().having(
          (e) => e.message,
          'message',
          allOf(contains('row 2'), contains('{nope}')),
        )),
      );
    });

    test('an alias declared in two files is an ambiguous reference', () {
      expect(
        () => generateWith(
          'alias,value\ntext/primary,{blue-500}\n',
          siblings: const {
            'color_primitive.csv': primitives,
            'other.csv': 'name,value\nblue-500,#000000\n',
          },
        ),
        throwsA(isA<PaletteFormatException>().having(
          (e) => e.message,
          'message',
          allOf(
            contains('ambiguous'),
            contains('color_primitive.csv'),
            contains('other.csv'),
          ),
        )),
      );
    });

    test('a reference loop is an error rather than a stack overflow', () {
      expect(
        () => generateWith(
          'alias,value\na,{b}\nb,{a}\n',
          siblings: const {},
        ),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('circular'))),
      );
    });

    test('an alias referencing itself is an error', () {
      expect(
        () => generateWith('alias,value\na,{a}\n', siblings: const {}),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('circular'))),
      );
    });

    test('a single-value palette cannot reference a mode-only alias', () {
      expect(
        () => generateWith(
          'alias,value\ntext/primary,{brand}\n',
          siblings: const {
            'other.csv': 'name,light,dark\nbrand,#2C6BED,#4C8DFF\n',
          },
        ),
        throwsA(isA<PaletteFormatException>().having(
          (e) => e.message,
          'message',
          contains('no plain value column'),
        )),
      );
    });

    test('braces are only a reference when they are the whole cell', () {
      expect(
        () => generateWith(
          'alias,value\ntext/primary,#FF{0}000\n',
          siblings: const {},
        ),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('Invalid color'))),
      );
    });
  });

  group('scanAliases', () {
    test('collects aliases with their raw per-mode values', () {
      final aliases = scanAliases(
        'semantic.csv',
        'alias,light,dark\ntext/primary,#212529,{gray-100}\n',
      );
      expect(aliases.keys, ['text/primary']);
      expect(aliases['text/primary']!.fileName, 'semantic.csv');
      expect(aliases['text/primary']!.valuesByMode,
          {'light': '#212529', 'dark': '{gray-100}'});
    });

    test('a malformed sibling contributes nothing instead of throwing', () {
      expect(scanAliases('broken.csv', ''), isEmpty);
      expect(scanAliases('broken.csv', 'name,value\n,,\n'), isEmpty);
      // A bad hex is not this function's problem — building that file reports it.
      expect(
        scanAliases('broken.csv', 'name,value\nx,not-a-color\n').keys,
        ['x'],
      );
    });
  });

  group('line endings', () {
    const expectedNames = ['white', 'black'];

    test('CRLF is parsed', () {
      final source =
          generate('name,value\r\nWhite,#FFFFFF\r\nBlack,#000000\r\n');
      for (final name in expectedNames) {
        expect(source, contains('static const Color $name = '));
      }
    });

    test('LF only is parsed', () {
      // Regression: the csv package defaults to eol '\r\n' and does not detect
      // anything else, so an LF-only export parsed as one single row. Every CSV
      // committed to this repo is LF-only.
      final source = generate('name,value\nWhite,#FFFFFF\nBlack,#000000\n');
      for (final name in expectedNames) {
        expect(source, contains('static const Color $name = '));
      }
    });

    test('legacy CR only is parsed', () {
      final source = generate('name,value\rWhite,#FFFFFF\rBlack,#000000\r');
      for (final name in expectedNames) {
        expect(source, contains('static const Color $name = '));
      }
    });

    test('a file without a trailing newline is parsed', () {
      final source = generate('name,value\nWhite,#FFFFFF');
      expect(source, contains('static const Color white = Color(0xFFFFFFFF);'));
    });
  });

  group('row tolerance', () {
    test('a two column CSV does not blow up on the missing comment', () {
      // Regression: `data[2]` threw RangeError, which was swallowed into a
      // warning, leaving no generated file behind at all.
      final source = generate('name,value\nWhite,#FFFFFF\n');
      expect(source, contains('/// `White`\n'));
      expect(source, contains('static const Color white = Color(0xFFFFFFFF);'));
    });

    test('trailing spreadsheet padding rows are skipped', () {
      final source = generate(
        'name,value,Comment,,,\n'
        'White,#FFFFFF,Comment test,,,\n'
        ',,,,,\n'
        ',,,,,\n',
      );
      expect(source, contains('Contains 1 color.'));
      expect(source, isNot(contains('Error')));
    });

    test('numeric aliases and values survive', () {
      // Regression: the csv package parsed these as `int`, which crashed the
      // `String` cast and stripped the leading zeros off the value.
      final source = generate('name,value\n100,000000\n');
      expect(
          source, contains('static const Color color100 = Color(0xFF000000);'));
    });

    test('a multi-line comment cell stays inside the doc comment', () {
      final source = generate('name,value,comment\nWhite,#FFFFFF,"one\ntwo"\n');
      expect(source, contains('/// `White` - one two\n'));
    });

    test('a value without a name is an error', () {
      expect(
        () => generate('name,value\n,#FFFFFF\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('row 2'))),
      );
    });

    test('a name without a value is an error', () {
      expect(
        () => generate('name,value\nWhite,\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('"White"'))),
      );
    });

    test('an unparseable value is an error naming the row', () {
      expect(
        () => generate('name,value\nWhite,rgba(0,0,0,.5)\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('row 2'))),
      );
    });
  });

  group('header mapping', () {
    test('columns are found by name, in any order', () {
      final warnings = <String>[];
      final source = generate(
        'Description,Hex,Token\n'
        'Default body text,#212529,text/primary\n',
        warnings: warnings,
      );
      expect(source, contains('/// `text/primary` - Default body text'));
      expect(source, contains('static const Color textPrimary'));
      expect(warnings, isEmpty);
    });

    test('an unrecognised header falls back to column order and warns', () {
      final warnings = <String>[];
      final source = generate('foo,bar\nWhite,#FFFFFF\n', warnings: warnings);
      expect(source, contains('static const Color white'));
      expect(warnings.single, contains('Falling back to column order'));
    });
  });

  group('naming', () {
    test('aliases that collide are an error rather than a silent overwrite',
        () {
      expect(
        () => generate(
            'name,value\ntext/primary,#000000\nText-Primary,#FFFFFF\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('textPrimary'))),
      );
    });

    test('a repeated alias is an error', () {
      expect(
        () => generate('name,value\nWhite,#FFFFFF\nWhite,#FFFFFE\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('more than once'))),
      );
    });

    test('an alias matching the class name only in case is left alone', () {
      // Members are lowerCamelCase and class names are PascalCase, so
      // `colorTest` inside `class ColorTest` is legal Dart.
      final source = generate('name,value\ncolor-test,#FFFFFF\n');
      expect(source, contains('static const Color colorTest'));
    });

    test('an alias colliding with byAlias is pushed aside', () {
      final source = generate('name,value\nby-alias,#FFFFFF\n');
      expect(source, contains('static const Color colorByAlias'));
    });

    test('a partly non-ASCII alias warns that part of it was dropped', () {
      // `경고/background` yields `background` — a usable name, but the `경고`
      // qualifier is gone, and nothing else would have said so.
      final warnings = <String>[];
      final source = generate(
        'alias,value\n경고/background,#FFF4E6\n',
        warnings: warnings,
      );
      expect(source, contains('static const Color background = '));
      expect(
        warnings.single,
        allOf(
          contains('row 2'),
          contains('경고/background'),
          contains('"background"'),
          contains('"code"'),
        ),
      );
    });

    test('a code value suppresses the non-ASCII warning', () {
      final warnings = <String>[];
      final source = generate(
        'alias,value,code\n'
        '경고/background,#FFF4E6,warningSurface\n'
        '경고/배경,#FFF4E6,warningSurfaceAlt\n',
        warnings: warnings,
      );
      expect(source, contains('static const Color warningSurface = '));
      expect(source, contains('static const Color warningSurfaceAlt = '));
      expect(warnings, isEmpty);
    });

    test('a plain ASCII alias never warns', () {
      final warnings = <String>[];
      generate(
        'alias,value\ntext/primary,#212529\nBlue Gray 50,#F8F9FA\n100,#FFFFFF\n',
        warnings: warnings,
      );
      expect(warnings, isEmpty);
    });

    test('a fully non-ASCII alias is an error that points at the code column',
        () {
      expect(
        () => generate('name,value\n브랜드/파랑,#2C6BED\n'),
        throwsA(isA<PaletteFormatException>().having(
          (e) => e.message,
          'message',
          allOf(contains('row 2'), contains('"code"')),
        )),
      );
    });

    test('a code value overrides the derived name', () {
      final source = generate(
        'alias,value,code,description\n'
        '브랜드/파랑,#2C6BED,brandBlue,Agreed with design\n'
        'text/primary,#212529,,Derived automatically\n',
      );
      expect(source, contains('/// `브랜드/파랑` - Agreed with design'));
      expect(source, contains('static const Color brandBlue'));
      expect(source, contains('static const Color textPrimary'));
      // The map still keys on the alias the designer wrote.
      expect(source, contains("'브랜드/파랑': brandBlue,"));
    });

    test('a code value resolves what would have been a name collision', () {
      final source = generate(
        'alias,value,code\n'
        'text/primary,#212529,\n'
        'text-primary,#868E96,textSecondaryAlt\n',
      );
      expect(source, contains('static const Color textPrimary'));
      expect(source, contains('static const Color textSecondaryAlt'));
    });

    test('a code value is taken literally, not re-cased', () {
      final source =
          generate('alias,value,code\ntext/primary,#212529,TEXT_1\n');
      expect(source, contains('static const Color TEXT_1'));
    });

    test('an unusable code value is an error naming the row', () {
      for (final code in <String>[
        '1st',
        'text primary',
        'text-primary',
        '_hidden',
        'new'
      ]) {
        expect(
          () => generate('alias,value,code\ntext/primary,#212529,$code\n'),
          throwsA(isA<PaletteFormatException>()
              .having((e) => e.message, 'message', contains('row 2'))),
          reason: 'expected code "$code" to be rejected',
        );
      }
    });

    test('a code value colliding with byAlias is an error, not a rename', () {
      expect(
        () => generate('alias,value,code\ntext/primary,#212529,byAlias\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('already used'))),
      );
    });

    test('quotes and dollars in an alias are escaped in the map key', () {
      final source = generate("name,value\nit's \$100,#FFFFFF\n");
      expect(source, contains(r"'it\'s \$100':"));
    });
  });

  group('options', () {
    test('colorPrefix restores the pre-2.0.0 naming', () {
      final source = generate(
        'name,value\ntext/primary,#212529\n',
        options: const PaletteOptions(colorPrefix: true),
      );
      expect(source, contains('static const Color colorTextPrimary'));
    });

    test('hexAlphaPosition.leading reads 8 digits as #AARRGGBB', () {
      final source = generate(
        'name,value\nscrim,#80000000\n',
        options:
            const PaletteOptions(hexAlphaPosition: HexAlphaPosition.leading),
      );
      expect(source, contains('Color(0x80000000)'));
    });

    test('generateAliasMap can be turned off', () {
      final source = generate(
        'name,value\nWhite,#FFFFFF\n',
        options: const PaletteOptions(generateAliasMap: false),
      );
      expect(source, isNot(contains('byAlias')));
      expect(source, contains('static const Color white'));
    });

    test('fromConfig reports unknown keys and rejects bad values', () {
      final warnings = <String>[];
      PaletteOptions.fromConfig(
        <String, dynamic>{'colorPrefix': true},
        onWarning: warnings.add,
      );
      expect(warnings.single, contains('Unknown option "colorPrefix"'));

      expect(
        () =>
            PaletteOptions.fromConfig(<String, dynamic>{'color_prefix': 'yes'}),
        throwsA(isA<PaletteFormatException>()),
      );
      expect(
        () => PaletteOptions.fromConfig(
            <String, dynamic>{'hex_alpha_position': 'middle'}),
        throwsA(isA<PaletteFormatException>()),
      );
    });
  });

  group('decodeCsvBytes', () {
    test('a UTF-8 BOM is stripped', () {
      final bytes = <int>[0xEF, 0xBB, 0xBF, ...utf8.encode('name,value\n')];
      expect(decodeCsvBytes(bytes), 'name,value\n');
    });

    test('plain UTF-8 including Korean text round-trips', () {
      expect(decodeCsvBytes(utf8.encode('이름,값\n')), '이름,값\n');
    });

    test('a UTF-16 BOM is reported as such', () {
      expect(
        () => decodeCsvBytes(<int>[0xFF, 0xFE, 0x00]),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('UTF-16'))),
      );
    });

    test('a legacy code page gets an actionable message', () {
      // "가" in CP949.
      expect(
        () => decodeCsvBytes(<int>[0xB0, 0xA1, 0x2C, 0x0A]),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('CSV UTF-8'))),
      );
    });
  });
}
