import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:project_color_palette/generator/palette_exception.dart';
import 'package:project_color_palette/generator/palette_options.dart';
import 'package:project_color_palette/generator/palette_source_builder.dart';

String generate(
  String csv, {
  String fileName = 'color_test.csv',
  PaletteOptions options = const PaletteOptions(),
  List<String>? warnings,
}) {
  return PaletteSourceBuilder(options: options).build(
    csvFileName: fileName,
    csvContent: csv,
    onWarning: warnings?.add,
  );
}

void main() {
  group('golden output', () {
    test('a multi-color palette closes its class exactly once', () {
      // Regression: `buffer.writeln('}')` used to sit inside the row loop, so
      // any CSV with more than one color produced uncompilable Dart. Every
      // committed example happened to have exactly one row.
      final source = generate(
        'alias,value,description\n'
        'text/primary,#212529,Default body text\n'
        'gray-100,#F1F3F5,\n'
        'overlay/scrim,#00000080,50% black\n',
        fileName: 'semantic_light.csv',
      );

      expect(source, '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by project_color_palette from 'semantic_light.csv'.
//
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:flutter/material.dart';

/// Color palette generated from `semantic_light.csv`.
///
/// Contains 3 colors.
class SemanticLight {
  const SemanticLight._();

  /// `text/primary` - Default body text
  static const Color textPrimary = Color(0xFF212529);

  /// `gray-100`
  static const Color gray100 = Color(0xFFF1F3F5);

  /// `overlay/scrim` - 50% black
  static const Color overlayScrim = Color(0x80000000);

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{
    'text/primary': textPrimary,
    'gray-100': gray100,
    'overlay/scrim': overlayScrim,
  };
}
''');
    });

    test('a palette with no data rows is still valid Dart', () {
      // Regression: zero rows used to emit `class X {` with no closing brace.
      final warnings = <String>[];
      final source = generate(
        'name,value,comment\n',
        fileName: 'color_empty.csv',
        warnings: warnings,
      );

      expect(source, '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by project_color_palette from 'color_empty.csv'.
//
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:flutter/material.dart';

/// Color palette generated from `color_empty.csv`.
///
/// Contains 0 colors.
class ColorEmpty {
  const ColorEmpty._();

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{};
}
''');
      expect(warnings, isEmpty);
    });

    test('an entirely empty file generates an empty palette and warns', () {
      final warnings = <String>[];
      final source = generate('', warnings: warnings);
      expect(source, contains('class ColorTest {'));
      expect(source.split('\n').where((line) => line == '}').length, 1);
      expect(warnings.single, contains('empty'));
    });
  });

  group('line endings', () {
    const expectedNames = ['white', 'black'];

    test('CRLF is parsed', () {
      final source =
          generate('name,value\r\nWhite,#FFFFFF\r\nBlack,#000000\r\n');
      for (final name in expectedNames) {
        expect(source, contains('static const Color $name = '));
      }
    });

    test('LF only is parsed', () {
      // Regression: the csv package defaults to eol '\r\n' and does not detect
      // anything else, so an LF-only export parsed as one single row. Every CSV
      // committed to this repo is LF-only.
      final source = generate('name,value\nWhite,#FFFFFF\nBlack,#000000\n');
      for (final name in expectedNames) {
        expect(source, contains('static const Color $name = '));
      }
    });

    test('legacy CR only is parsed', () {
      final source = generate('name,value\rWhite,#FFFFFF\rBlack,#000000\r');
      for (final name in expectedNames) {
        expect(source, contains('static const Color $name = '));
      }
    });

    test('a file without a trailing newline is parsed', () {
      final source = generate('name,value\nWhite,#FFFFFF');
      expect(source, contains('static const Color white = Color(0xFFFFFFFF);'));
    });
  });

  group('row tolerance', () {
    test('a two column CSV does not blow up on the missing comment', () {
      // Regression: `data[2]` threw RangeError, which was swallowed into a
      // warning, leaving no generated file behind at all.
      final source = generate('name,value\nWhite,#FFFFFF\n');
      expect(source, contains('/// `White`\n'));
      expect(source, contains('static const Color white = Color(0xFFFFFFFF);'));
    });

    test('trailing spreadsheet padding rows are skipped', () {
      final source = generate(
        'name,value,Comment,,,\n'
        'White,#FFFFFF,Comment test,,,\n'
        ',,,,,\n'
        ',,,,,\n',
      );
      expect(source, contains('Contains 1 color.'));
      expect(source, isNot(contains('Error')));
    });

    test('numeric aliases and values survive', () {
      // Regression: the csv package parsed these as `int`, which crashed the
      // `String` cast and stripped the leading zeros off the value.
      final source = generate('name,value\n100,000000\n');
      expect(
          source, contains('static const Color color100 = Color(0xFF000000);'));
    });

    test('a multi-line comment cell stays inside the doc comment', () {
      final source = generate('name,value,comment\nWhite,#FFFFFF,"one\ntwo"\n');
      expect(source, contains('/// `White` - one two\n'));
    });

    test('a value without a name is an error', () {
      expect(
        () => generate('name,value\n,#FFFFFF\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('row 2'))),
      );
    });

    test('a name without a value is an error', () {
      expect(
        () => generate('name,value\nWhite,\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('"White"'))),
      );
    });

    test('an unparseable value is an error naming the row', () {
      expect(
        () => generate('name,value\nWhite,rgba(0,0,0,.5)\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('row 2'))),
      );
    });
  });

  group('header mapping', () {
    test('columns are found by name, in any order', () {
      final warnings = <String>[];
      final source = generate(
        'Description,Hex,Token\n'
        'Default body text,#212529,text/primary\n',
        warnings: warnings,
      );
      expect(source, contains('/// `text/primary` - Default body text'));
      expect(source, contains('static const Color textPrimary'));
      expect(warnings, isEmpty);
    });

    test('an unrecognised header falls back to column order and warns', () {
      final warnings = <String>[];
      final source = generate('foo,bar\nWhite,#FFFFFF\n', warnings: warnings);
      expect(source, contains('static const Color white'));
      expect(warnings.single, contains('Falling back to column order'));
    });
  });

  group('naming', () {
    test('aliases that collide are an error rather than a silent overwrite',
        () {
      expect(
        () => generate(
            'name,value\ntext/primary,#000000\nText-Primary,#FFFFFF\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('textPrimary'))),
      );
    });

    test('a repeated alias is an error', () {
      expect(
        () => generate('name,value\nWhite,#FFFFFF\nWhite,#FFFFFE\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('more than once'))),
      );
    });

    test('an alias matching the class name only in case is left alone', () {
      // Members are lowerCamelCase and class names are PascalCase, so
      // `colorTest` inside `class ColorTest` is legal Dart.
      final source = generate('name,value\ncolor-test,#FFFFFF\n');
      expect(source, contains('static const Color colorTest'));
    });

    test('an alias colliding with byAlias is pushed aside', () {
      final source = generate('name,value\nby-alias,#FFFFFF\n');
      expect(source, contains('static const Color colorByAlias'));
    });

    test('a non-ASCII alias is an error that points at the code column', () {
      expect(
        () => generate('name,value\n브랜드/파랑,#2C6BED\n'),
        throwsA(isA<PaletteFormatException>().having(
          (e) => e.message,
          'message',
          allOf(contains('row 2'), contains('"code"')),
        )),
      );
    });

    test('a code value overrides the derived name', () {
      final source = generate(
        'alias,value,code,description\n'
        '브랜드/파랑,#2C6BED,brandBlue,Agreed with design\n'
        'text/primary,#212529,,Derived automatically\n',
      );
      expect(source, contains('/// `브랜드/파랑` - Agreed with design'));
      expect(source, contains('static const Color brandBlue'));
      expect(source, contains('static const Color textPrimary'));
      // The map still keys on the alias the designer wrote.
      expect(source, contains("'브랜드/파랑': brandBlue,"));
    });

    test('a code value resolves what would have been a name collision', () {
      final source = generate(
        'alias,value,code\n'
        'text/primary,#212529,\n'
        'text-primary,#868E96,textSecondaryAlt\n',
      );
      expect(source, contains('static const Color textPrimary'));
      expect(source, contains('static const Color textSecondaryAlt'));
    });

    test('a code value is taken literally, not re-cased', () {
      final source =
          generate('alias,value,code\ntext/primary,#212529,TEXT_1\n');
      expect(source, contains('static const Color TEXT_1'));
    });

    test('an unusable code value is an error naming the row', () {
      for (final code in <String>[
        '1st',
        'text primary',
        'text-primary',
        '_hidden',
        'new'
      ]) {
        expect(
          () => generate('alias,value,code\ntext/primary,#212529,$code\n'),
          throwsA(isA<PaletteFormatException>()
              .having((e) => e.message, 'message', contains('row 2'))),
          reason: 'expected code "$code" to be rejected',
        );
      }
    });

    test('a code value colliding with byAlias is an error, not a rename', () {
      expect(
        () => generate('alias,value,code\ntext/primary,#212529,byAlias\n'),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('already used'))),
      );
    });

    test('quotes and dollars in an alias are escaped in the map key', () {
      final source = generate("name,value\nit's \$100,#FFFFFF\n");
      expect(source, contains(r"'it\'s \$100':"));
    });
  });

  group('options', () {
    test('colorPrefix restores the pre-2.0.0 naming', () {
      final source = generate(
        'name,value\ntext/primary,#212529\n',
        options: const PaletteOptions(colorPrefix: true),
      );
      expect(source, contains('static const Color colorTextPrimary'));
    });

    test('hexAlphaPosition.leading reads 8 digits as #AARRGGBB', () {
      final source = generate(
        'name,value\nscrim,#80000000\n',
        options:
            const PaletteOptions(hexAlphaPosition: HexAlphaPosition.leading),
      );
      expect(source, contains('Color(0x80000000)'));
    });

    test('generateAliasMap can be turned off', () {
      final source = generate(
        'name,value\nWhite,#FFFFFF\n',
        options: const PaletteOptions(generateAliasMap: false),
      );
      expect(source, isNot(contains('byAlias')));
      expect(source, contains('static const Color white'));
    });

    test('fromConfig reports unknown keys and rejects bad values', () {
      final warnings = <String>[];
      PaletteOptions.fromConfig(
        <String, dynamic>{'colorPrefix': true},
        onWarning: warnings.add,
      );
      expect(warnings.single, contains('Unknown option "colorPrefix"'));

      expect(
        () =>
            PaletteOptions.fromConfig(<String, dynamic>{'color_prefix': 'yes'}),
        throwsA(isA<PaletteFormatException>()),
      );
      expect(
        () => PaletteOptions.fromConfig(
            <String, dynamic>{'hex_alpha_position': 'middle'}),
        throwsA(isA<PaletteFormatException>()),
      );
    });
  });

  group('decodeCsvBytes', () {
    test('a UTF-8 BOM is stripped', () {
      final bytes = <int>[0xEF, 0xBB, 0xBF, ...utf8.encode('name,value\n')];
      expect(decodeCsvBytes(bytes), 'name,value\n');
    });

    test('plain UTF-8 including Korean text round-trips', () {
      expect(decodeCsvBytes(utf8.encode('이름,값\n')), '이름,값\n');
    });

    test('a UTF-16 BOM is reported as such', () {
      expect(
        () => decodeCsvBytes(<int>[0xFF, 0xFE, 0x00]),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('UTF-16'))),
      );
    });

    test('a legacy code page gets an actionable message', () {
      // "가" in CP949.
      expect(
        () => decodeCsvBytes(<int>[0xB0, 0xA1, 0x2C, 0x0A]),
        throwsA(isA<PaletteFormatException>()
            .having((e) => e.message, 'message', contains('CSV UTF-8'))),
      );
    });
  });
}
