targets:
  $default:
    builders:
      palette_generator:
        generate_for:
          - assets/color_palette/*.csv

builders:
  palette_generator:
    import: "package:project_color_palette/generator/palette_generator.dart"
    builder_factories: ["paletteGeneratorBuilder"]
    build_extensions: {"assets/color_palette/{{}}.csv": ["lib/palette/{{}}.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["csv|glob"]
