// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by project_color_palette from 'color_primitive.csv'.
//
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:flutter/material.dart';

/// Color palette generated from `color_primitive.csv`.
///
/// Contains 9 colors.
class ColorPrimitive {
  const ColorPrimitive._();

  /// `gray-0`
  static const Color gray0 = Color(0xFFFFFFFF);

  /// `gray-50`
  static const Color gray50 = Color(0xFFF8F9FA);

  /// `gray-100`
  static const Color gray100 = Color(0xFFF1F3F5);

  /// `gray-500`
  static const Color gray500 = Color(0xFFADB5BD);

  /// `gray-900`
  static const Color gray900 = Color(0xFF212529);

  /// `blue-500` - Brand blue
  static const Color blue500 = Color(0xFF2C6BED);

  /// `blue-600`
  static const Color blue600 = Color(0xFF1F55C4);

  /// `red-500`
  static const Color red500 = Color(0xFFE03131);

  /// `transparent` - Fully transparent (8 digit hex is #RRGGBBAA)
  static const Color transparent = Color(0x00FFFFFF);

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{
    'gray-0': gray0,
    'gray-50': gray50,
    'gray-100': gray100,
    'gray-500': gray500,
    'gray-900': gray900,
    'blue-500': blue500,
    'blue-600': blue600,
    'red-500': red500,
    'transparent': transparent,
  };
}
