// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by project_color_palette from 'semantic_light.csv'.
//
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:flutter/material.dart';

/// Color palette generated from `semantic_light.csv`.
///
/// Contains 13 colors.
class SemanticLight {
  const SemanticLight._();

  /// `text/primary` - Default body text
  static const Color textPrimary = Color(0xFF212529);

  /// `text/secondary`
  static const Color textSecondary = Color(0xFF868E96);

  /// `text/on-brand`
  static const Color textOnBrand = Color(0xFFFFFFFF);

  /// `Background Default` - Spaces in the alias work too
  static const Color backgroundDefault = Color(0xFFFFFFFF);

  /// `background/subtle`
  static const Color backgroundSubtle = Color(0xFFF8F9FA);

  /// `border/default`
  static const Color borderDefault = Color(0xFFDEE2E6);

  /// `action/primary`
  static const Color actionPrimary = Color(0xFF2C6BED);

  /// `action/primary-pressed`
  static const Color actionPrimaryPressed = Color(0xFF1F55C4);

  /// `overlay/scrim` - 50% black overlay
  static const Color overlayScrim = Color(0x80000000);

  /// `brandAccentSubtle` - camelCase is not re-cased
  static const Color brandAccentSubtle = Color(0xFFE7F0FF);

  /// `100` - A numeric alias needs a color prefix
  static const Color color100 = Color(0xFFF1F3F5);

  /// `new` - A Dart keyword needs a color prefix
  static const Color colorNew = Color(0xFFE03131);

  /// `경고/배경` - Non-ASCII alias needs an agreed code
  static const Color warningSurface = Color(0xFFFFF4E6);

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{
    'text/primary': textPrimary,
    'text/secondary': textSecondary,
    'text/on-brand': textOnBrand,
    'Background Default': backgroundDefault,
    'background/subtle': backgroundSubtle,
    'border/default': borderDefault,
    'action/primary': actionPrimary,
    'action/primary-pressed': actionPrimaryPressed,
    'overlay/scrim': overlayScrim,
    'brandAccentSubtle': brandAccentSubtle,
    '100': color100,
    'new': colorNew,
    '경고/배경': warningSurface,
  };
}
