// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by project_color_palette from 'semantic.csv'.
//
// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:flutter/material.dart';

/// Color palette generated from `semantic.csv` (light mode).
///
/// Contains 13 colors.
class SemanticLight {
  const SemanticLight._();

  /// `text/primary` - References the primitive palette
  static const Color textPrimary = Color(0xFF212529);

  /// `text/secondary`
  static const Color textSecondary = Color(0xFF868E96);

  /// `text/on-brand`
  static const Color textOnBrand = Color(0xFFFFFFFF);

  /// `Background Default` - A literal is still fine
  static const Color backgroundDefault = Color(0xFFFFFFFF);

  /// `background/subtle`
  static const Color backgroundSubtle = Color(0xFFF8F9FA);

  /// `border/default`
  static const Color borderDefault = Color(0xFFDEE2E6);

  /// `action/primary`
  static const Color actionPrimary = Color(0xFF2C6BED);

  /// `action/primary-pressed`
  static const Color actionPrimaryPressed = Color(0xFF1F55C4);

  /// `overlay/scrim` - 50% black overlay
  static const Color overlayScrim = Color(0x80000000);

  /// `brandAccentSubtle` - camelCase is not re-cased
  static const Color brandAccentSubtle = Color(0xFFE7F0FF);

  /// `100` - A numeric alias needs a color prefix
  static const Color color100 = Color(0xFFF1F3F5);

  /// `new` - A Dart keyword needs a color prefix
  static const Color colorNew = Color(0xFFE03131);

  /// `경고/배경` - Non-ASCII alias needs an agreed code
  static const Color warningSurface = Color(0xFFFFF4E6);

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{
    'text/primary': textPrimary,
    'text/secondary': textSecondary,
    'text/on-brand': textOnBrand,
    'Background Default': backgroundDefault,
    'background/subtle': backgroundSubtle,
    'border/default': borderDefault,
    'action/primary': actionPrimary,
    'action/primary-pressed': actionPrimaryPressed,
    'overlay/scrim': overlayScrim,
    'brandAccentSubtle': brandAccentSubtle,
    '100': color100,
    'new': colorNew,
    '경고/배경': warningSurface,
  };
}

/// Color palette generated from `semantic.csv` (dark mode).
///
/// Contains 13 colors.
class SemanticDark {
  const SemanticDark._();

  /// `text/primary` - References the primitive palette
  static const Color textPrimary = Color(0xFFF1F3F5);

  /// `text/secondary`
  static const Color textSecondary = Color(0xFFADB5BD);

  /// `text/on-brand`
  static const Color textOnBrand = Color(0xFFFFFFFF);

  /// `Background Default` - A literal is still fine
  static const Color backgroundDefault = Color(0xFF16191D);

  /// `background/subtle`
  static const Color backgroundSubtle = Color(0xFF212529);

  /// `border/default`
  static const Color borderDefault = Color(0xFF343A40);

  /// `action/primary`
  static const Color actionPrimary = Color(0xFF4C8DFF);

  /// `action/primary-pressed`
  static const Color actionPrimaryPressed = Color(0xFF2C6BED);

  /// `overlay/scrim` - 50% black overlay
  static const Color overlayScrim = Color(0xB3000000);

  /// `brandAccentSubtle` - camelCase is not re-cased
  static const Color brandAccentSubtle = Color(0xFF16233D);

  /// `100` - A numeric alias needs a color prefix
  static const Color color100 = Color(0xFF212529);

  /// `new` - A Dart keyword needs a color prefix
  static const Color colorNew = Color(0xFFFF6B6B);

  /// `경고/배경` - Non-ASCII alias needs an agreed code
  static const Color warningSurface = Color(0xFF3D2E16);

  /// Every color in this palette, keyed by its alias
  /// exactly as written in the CSV.
  static const Map<String, Color> byAlias = <String, Color>{
    'text/primary': textPrimary,
    'text/secondary': textSecondary,
    'text/on-brand': textOnBrand,
    'Background Default': backgroundDefault,
    'background/subtle': backgroundSubtle,
    'border/default': borderDefault,
    'action/primary': actionPrimary,
    'action/primary-pressed': actionPrimaryPressed,
    'overlay/scrim': overlayScrim,
    'brandAccentSubtle': brandAccentSubtle,
    '100': color100,
    'new': colorNew,
    '경고/배경': warningSurface,
  };
}

/// The palette above, resolved through the active theme.
///
/// Register it once:
///
/// ```dart
/// ThemeData(extensions: const [Semantic.light])
/// ```
///
/// then read it with `Semantic.of(context).textPrimary`.
class Semantic extends ThemeExtension<Semantic> {
  const Semantic({
    required this.textPrimary,
    required this.textSecondary,
    required this.textOnBrand,
    required this.backgroundDefault,
    required this.backgroundSubtle,
    required this.borderDefault,
    required this.actionPrimary,
    required this.actionPrimaryPressed,
    required this.overlayScrim,
    required this.brandAccentSubtle,
    required this.color100,
    required this.colorNew,
    required this.warningSurface,
  });

  /// The light mode palette.
  static const Semantic light = Semantic(
    textPrimary: SemanticLight.textPrimary,
    textSecondary: SemanticLight.textSecondary,
    textOnBrand: SemanticLight.textOnBrand,
    backgroundDefault: SemanticLight.backgroundDefault,
    backgroundSubtle: SemanticLight.backgroundSubtle,
    borderDefault: SemanticLight.borderDefault,
    actionPrimary: SemanticLight.actionPrimary,
    actionPrimaryPressed: SemanticLight.actionPrimaryPressed,
    overlayScrim: SemanticLight.overlayScrim,
    brandAccentSubtle: SemanticLight.brandAccentSubtle,
    color100: SemanticLight.color100,
    colorNew: SemanticLight.colorNew,
    warningSurface: SemanticLight.warningSurface,
  );

  /// The dark mode palette.
  static const Semantic dark = Semantic(
    textPrimary: SemanticDark.textPrimary,
    textSecondary: SemanticDark.textSecondary,
    textOnBrand: SemanticDark.textOnBrand,
    backgroundDefault: SemanticDark.backgroundDefault,
    backgroundSubtle: SemanticDark.backgroundSubtle,
    borderDefault: SemanticDark.borderDefault,
    actionPrimary: SemanticDark.actionPrimary,
    actionPrimaryPressed: SemanticDark.actionPrimaryPressed,
    overlayScrim: SemanticDark.overlayScrim,
    brandAccentSubtle: SemanticDark.brandAccentSubtle,
    color100: SemanticDark.color100,
    colorNew: SemanticDark.colorNew,
    warningSurface: SemanticDark.warningSurface,
  );

  /// `text/primary` - References the primitive palette
  final Color textPrimary;

  /// `text/secondary`
  final Color textSecondary;

  /// `text/on-brand`
  final Color textOnBrand;

  /// `Background Default` - A literal is still fine
  final Color backgroundDefault;

  /// `background/subtle`
  final Color backgroundSubtle;

  /// `border/default`
  final Color borderDefault;

  /// `action/primary`
  final Color actionPrimary;

  /// `action/primary-pressed`
  final Color actionPrimaryPressed;

  /// `overlay/scrim` - 50% black overlay
  final Color overlayScrim;

  /// `brandAccentSubtle` - camelCase is not re-cased
  final Color brandAccentSubtle;

  /// `100` - A numeric alias needs a color prefix
  final Color color100;

  /// `new` - A Dart keyword needs a color prefix
  final Color colorNew;

  /// `경고/배경` - Non-ASCII alias needs an agreed code
  final Color warningSurface;

  /// The palette registered on the closest [Theme].
  static Semantic of(BuildContext context) =>
      Theme.of(context).extension<Semantic>()!;

  @override
  Semantic copyWith({
    Color? textPrimary,
    Color? textSecondary,
    Color? textOnBrand,
    Color? backgroundDefault,
    Color? backgroundSubtle,
    Color? borderDefault,
    Color? actionPrimary,
    Color? actionPrimaryPressed,
    Color? overlayScrim,
    Color? brandAccentSubtle,
    Color? color100,
    Color? colorNew,
    Color? warningSurface,
  }) {
    return Semantic(
      textPrimary: textPrimary ?? this.textPrimary,
      textSecondary: textSecondary ?? this.textSecondary,
      textOnBrand: textOnBrand ?? this.textOnBrand,
      backgroundDefault: backgroundDefault ?? this.backgroundDefault,
      backgroundSubtle: backgroundSubtle ?? this.backgroundSubtle,
      borderDefault: borderDefault ?? this.borderDefault,
      actionPrimary: actionPrimary ?? this.actionPrimary,
      actionPrimaryPressed: actionPrimaryPressed ?? this.actionPrimaryPressed,
      overlayScrim: overlayScrim ?? this.overlayScrim,
      brandAccentSubtle: brandAccentSubtle ?? this.brandAccentSubtle,
      color100: color100 ?? this.color100,
      colorNew: colorNew ?? this.colorNew,
      warningSurface: warningSurface ?? this.warningSurface,
    );
  }

  @override
  Semantic lerp(covariant ThemeExtension<Semantic>? other, double t) {
    if (other is! Semantic) return this;
    return Semantic(
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      textOnBrand: Color.lerp(textOnBrand, other.textOnBrand, t)!,
      backgroundDefault: Color.lerp(
        backgroundDefault,
        other.backgroundDefault,
        t,
      )!,
      backgroundSubtle: Color.lerp(
        backgroundSubtle,
        other.backgroundSubtle,
        t,
      )!,
      borderDefault: Color.lerp(borderDefault, other.borderDefault, t)!,
      actionPrimary: Color.lerp(actionPrimary, other.actionPrimary, t)!,
      actionPrimaryPressed: Color.lerp(
        actionPrimaryPressed,
        other.actionPrimaryPressed,
        t,
      )!,
      overlayScrim: Color.lerp(overlayScrim, other.overlayScrim, t)!,
      brandAccentSubtle: Color.lerp(
        brandAccentSubtle,
        other.brandAccentSubtle,
        t,
      )!,
      color100: Color.lerp(color100, other.color100, t)!,
      colorNew: Color.lerp(colorNew, other.colorNew, t)!,
      warningSurface: Color.lerp(warningSurface, other.warningSurface, t)!,
    );
  }
}
